parameters:
    facebook_rest_server.parameters.auth:
        app_id: %kpdz_facebook.rest_server.app_id%
        secret_id: %kpdz_facebook.rest_server.secret_id%
    facebook_rest_server.parameters.permissions: %kpdz_facebook.rest_server.permissions%
    facebook_rest_server.security.session_manager.class: "Kupids\Bundle\FaceBookRestServerBundle\Security\SessionManager"
    facebook_rest_server.data_manager.data_provider.class: "Kupids\Bundle\FacebookRestServerBundle\DataManager\DataProvider"
    facebook_rest_server.user_manager.class: "Kupids\Bundle\FaceBookRestServerBundle\Doctrine\UserManager"

services:
    facebook_rest_server.security.session:
        class: %facebook_rest_server.security.session_manager.class%
        arguments: [%facebook_rest_server.parameters.auth%]
    facebook_rest_server.data_manager.data_provider:
        class: %facebook_rest_server.data_manager.data_provider.class%
        arguments: [@service_container, @facebook_rest_server.user_manager, %facebook_rest_server.parameters.permissions%]
    facebook_rest_server.user_manager:
        class: %facebook_rest_server.user_manager.class%
        arguments: [@security.encoder_factory,@fos_user.util.username_canonicalizer,@fos_user.util.email_canonicalizer,@doctrine.orm.entity_manager,%fos_user.model.user.class%]