parameters:
    facebook_connect_rest.parameters.auth:
        app_id: %kpds_facebook.rest.app_id%
        secret_id: %kpds_facebook.rest.secret_id%
    facebook_connect_rest.parameters.permissions: %kpds_facebook.rest.permissions%
    facebook_connect_rest.security.session_manager.class: "Kpdz\FacebookConnectRestBundle\Security\SessionManager"
    facebook_connect_rest.grant_type.facebook_id.class: "Kpdz\FacebookConnectRestBundle\Security\RestCredentialGrantExtension"
    facebook_connect_rest.data_manager.data_provider.class: "Kpdz\FacebookConnectRestBundle\DataManager\DataProvider"
    facebook_connect_rest.user_manager.class: "Kpdz\FacebookConnectRestBundle\Doctrine\UserManager"

services:
    facebook_connect_rest.security.session:
        class: %facebook_connect_rest.security.session_manager.class%
        arguments: [%facebook_connect_rest.parameters.auth%]
    facebook_connect_rest.grant_type.facebook_id:
        class: %facebook_connect_rest.grant_type.facebook_id.class%
        tags:
            - { name: fos_oauth_server.grant_extension, uri: "http://api.kupids.dev/aouth/token" }
        arguments: [@facebook_connect_rest.user_manager]
    facebook_connect_rest.data_manager.data_provider:
        class: %facebook_connect_rest.data_manager.data_provider.class%
        arguments: [@service_container, @facebook_connect_rest.user_manager, %facebook_connect_rest.parameters.permissions%]
    facebook_connect_rest.user_manager:
        class: %facebook_connect_rest.user_manager.class%
        arguments: [@security.encoder_factory,@fos_user.util.username_canonicalizer,@fos_user.util.email_canonicalizer,@doctrine.orm.entity_manager,%fos_user.model.user.class%]